ARG CP_VERSION=5.4.3
ARG DB2_CONNECTOR_VERSION

FROM confluentinc/cp-kafka-connect-base:${CP_VERSION}

ENV JAVA_HOME=/usr/lib/jvm/zulu-8-amd64
ENV MAVEN_VERSION=3.6.3
ENV MAVEN_HOME=/usr/share/maven
ENV DB2_CONNECTOR_VERSION=${DB2_CONNECTOR_VERSION:-1.3.1.Final}

USER root

# to install maven and debezium-connector jars
RUN env && mkdir -p ${MAVEN_HOME} \
  && curl -o apache-maven-bin.tar.gz https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && tar -xzf apache-maven-bin.tar.gz -C ${MAVEN_HOME} --strip-components=1 \
  && rm -f apache-maven-bin.tar.gz \
  && ${MAVEN_HOME}/bin/mvn dependency:get -Dartifact=io.debezium:debezium-connector-db2:${DB2_CONNECTOR_VERSION}:jar -Dtransitive=true