ARG CP_VERSION=6.0.0
ARG DB2_CONNECTOR_VERSION=1.3.1.Final

FROM confluentinc/cp-kafka-connect-base:${CP_VERSION}

# to install maven and debezium-connector jars
RUN echo "export JAVA_HOME=/usr/lib/jvm/zulu-8-amd64" >> ~/.bashrc \
  && echo "export MAVEN_VERSION=3.6.3" >> ~/.bashrc \
  && echo "export MAVEN_HOME=/usr/share/maven" >> ~/.bashrc \
  && echo "export MAVEN_CONFIG=$HOME/.m2" >> ~/.bashrc \
  && echo "export PATH=$MAVEN_HOME/bin:$PATH" >> ~/.bashrc \
  && . ~/.bashrc \
  && mkdir -p ${MAVEN_HOME} \
  && curl -o apache-maven-bin.tar.gz https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && tar -xzf apache-maven-bin.tar.gz -C ${MAVEN_HOME} --strip-components=1 \
  && rm -f apache-maven-bin.tar.gz \
  && mvn dependency:get -Dartifact=io.debezium:debezium-connector-db2:${DB2_CONNECTOR_VERSION}:jar -Dtransitive=true